_id: 63039396515744002ce751af
title: Acquirer Transaction
description: Describe your new bucket
icon: view_stream
primary: transaction_id
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the transaction_id input
    options:
      position: bottom
  obje1:
    type: object
    title: obje1
    description: Description of the transaction_id input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 6
category: Logs
